# Site settings
title: Daniel Richards R
description: Personal website
url:  "https://dannyrichy.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
include:
  - self-notes
exclude: ["README.md"]
sass:
  style: compressed

collections:
  notes:
    output: true # This ensures each item gets its own page
    permalink: /notes/:name # Optional: Sets the URL structure for each note
